/****************************************************************************
 * Copyright (C) 2014 by Lukas Elsner                                       *
 *                                                                          *
 * This file is part of airport-sim.                                        *
 *                                                                          *
 ****************************************************************************/

/**
 * @file plane.h
 * @author Lukas Elsner
 * @date 01-09-2014
 * @brief Header containing the public accessible plane methods.
 *
 * A plane is generated by the landing thread and stored in a bay of the airport.
 *
 */
#ifndef PLANE_H
#define PLANE_H

/**
 *
 * @brief Forward declaration for plane
 *
 * */
typedef struct plane plane;

/**
 * @brief constructor for plane
 * @return A pointer to the plane structure, representing the created object
 *
 * After using this structure, it must be freed with plane_destroy(plane *)
 *
 * */
plane *plane_init();

/**
 * @brief Method for getting the name of a plane structure
 * @param plane* Pointer to structure to work on
 * @return A pointer to a string representation of passed structure. Must be freed by caller.
 *
 * */
char *plane_get_name(plane *);

/**
 * @brief Destructor for plane
 * @param plane* Pointer to structure to be freed
 *
 * */
void plane_destroy(plane *);

#endif /* PLANE_H */
